name: CI Pipeline

on:  
  push:  
    branches:  
      - main
  pull_request:

jobs:  
  build:  
    runs-on: ubuntu-latest

    services:  
      postgres:  
        image: postgres
        env:  
          POSTGRES_PASSWORD: example
        ports:  
          - 5432:5432
        options: >-  
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Build frontend
      run: docker build -t test-frontend ./frontend

    - name: Build backend
      run: docker build -t test-backend ./backend

    - name: Start Database & Backend Services
      run: docker compose up --build -d db backend

    - name: Wait for Database to Be Ready
      run: sleep 20

    - name: Check Running Containers
      run: docker ps -a

    - name: View Backend Logs (Only If Running)
      run: |
        if docker ps | grep -q "hedgehog-lab-test-backend-1"; then
          docker logs hedgehog-lab-test-backend-1;
        else
          echo "Backend container was never started!";
          exit 1;
        fi

    - name: Run Backend Health Check
      run: |
        echo "Waiting for backend..."
        sleep 30
        curl -f http://localhost:8000/healthz || exit 1

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag backend image for GHCR
      run: |
        REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker tag test-backend ghcr.io/${REPO_OWNER_LOWER}/hedgehog-lab-test-backend:latest

    - name: Push backend image to GHCR
      run: |
        REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${REPO_OWNER_LOWER}/hedgehog-lab-test-backend:latest
